# Generated by Django 3.2.25 on 2026-02-26 10:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_website', '0002_alter_contact_updated_date'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='contact',
            options={'ordering': ['created_date']},
        ),
    ]
